Getbyname
DamianBroglia/PF_Back pull request #44
Opened 2023-05-15 22:24 UTC by MarcosAdrianMuga

No estaban los get by name de hoteles ni de restaurantes. Para poder hacer bien el search los agregue (si estas leyendo esto aproba lo del front tambien)

2023-05-15 22:43 UTC, lucasguerendiain approved these changes

2023-05-15 23:15 UTC, gomezomar approved these changes

2023-05-16 12:46 UTC, EliasYanzon approved these changes

2023-05-16 16:37 UTC, lucasguerendiain requested changes
lo podes borrar solamente vos

2023-05-17 03:07 UTC, closed without merging